postinstall:
	rm -rf components next.config.js postcss.config.js tailwind.config.js
	cp -r ../../packages/components/src components
	cp -f ../../configurations/next/src/index.js next.config.js
	cp -f ../../configurations/postcss/src/index.js postcss.config.js
	cp -f ../../configurations/tailwind/src/index.js tailwind.config.js
