postinstall:
	ln -sf ../../packages/components/src components
	ln -sf ../../configurations/postcss/src/index.js postcss.config.js
	ln -sf ../../configurations/tailwind/src/index.js tailwind.config.js
